name: ericgruber.net
favicon: null
layout_spectrum: 0.51168
typography_spectrum: 0.21429865062236786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#5b2b14'
    - '#a57b62'
    - '#cfc6c2'
  brandStrength: 0.9001666808035225
  lightness: 0.7152720745652914
  saturation: 0.3978897675406188
  rhythmicContrast: 0.8102207481861115
purpose: []
