name: ericgruber.net
favicon: null
layout_spectrum: 0.51168
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7e7e7e'
    - '#464646'
    - '#acacac'
    - '#e1e1e1'
  brandStrength: 0.9001666808035225
  lightness: 0.7152720745652914
  saturation: 0.3978897675406188
  rhythmicContrast: 0.8102207481861115
purpose: []
